FROM golang:1.25-alpine AS builder

WORKDIR /build

RUN apk add --no-cache git gcc musl-dev
COPY go.mod go.sum ./
RUN go mod download
COPY . .

ARG SERVICE_NAME
RUN CGO_ENABLED=0 GOOS=linux go build -o /build/app ./cmd/${SERVICE_NAME}

FROM alpine:latest
WORKDIR /app
RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /build/app .

COPY --from=builder /build/docs ./docs

RUN mkdir -p /app/storage/files

CMD ["./app"]
